<?php

namespace RetsBundle\Repository;

/**
 * LeasedMlsPropertiesCursorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeasedMlsPropertiesCursorRepository extends \Doctrine\ORM\EntityRepository
{
}
