<?php

namespace RetsBundle\Repository;

/**
 * MlsPropertiesCursorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MlsPropertiesCursorRepository extends \Doctrine\ORM\EntityRepository
{
}
