<?php

namespace RetsBundle\Repository;

/**
 * RetsServersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetsServersRepository extends \Doctrine\ORM\EntityRepository
{
}
