services:
    rapp_loyalty.loyalty_api_client:
        class: RAPP\Bundle\LoyaltyBundle\Service\LoyaltyApiClient
        arguments:
            - %rapp_loyalty_api.url%
            - %rapp_loyalty_oauth.url%
            - %rapp_loyalty_oauth.client_id%
            - %rapp_loyalty_oauth.secret%
            - @jms_serializer
            - @logger
    rapp_loyalty.loyalty_service:
        class: RAPP\Bundle\LoyaltyBundle\Service\LoyaltyService
        arguments:
            - @rapp_loyalty.loyalty_api_client
            - @doctrine.orm.entity_manager
            - @jms_serializer
            - @logger
            
#    rapp_message.aws_sqs_client:
#        class: RAPP\MessageBundle\Service\AwsSqsClient
#        arguments:
#            - %aws.key%
#            - %aws.secret%
#            - %aws.region%
#            - @validator
#    rapp_loyalty.message_processor:
#        class: RAPP\Bundle\LoyaltyBundle\Service\LoyaltyMessageProcessor
#        arguments:
#            - @rapp_message.aws_sqs_client
#            - @validator
#            - @doctrine.orm.entity_manager
#            - @rapp_loyalty.exact_target_soap_client
#            - %rapp_exact_target.API%
#    rapp_loyalty.exact_target_soap_client:
#        class: RAPP\MessageBundle\Service\ExactTargetSoapClient
#        arguments:
#            - %exact_target.soap_api.brinker_username%
#            - %exact_target.soap_api.brinker_password%
#            - %exact_target.soap_api.brinker_wsdl%
#    rapp_loyalty.exact_target_message_service:
#        class: RAPP\Bundle\LoyaltyBundle\Service\ExactTargetMessageService
#        arguments:
#            - @doctrine.orm.entity_manager
#            - @rapp_loyalty.exact_target_soap_client
