services:
    codewise_loyalty.loyalty_api_client:
        class: codewise\Bundle\LoyaltyBundle\Service\LoyaltyApiClient
        arguments:
            - %codewise_loyalty_api.url%
            - %codewise_loyalty_oauth.url%
            - %codewise_loyalty_oauth.client_id%
            - %codewise_loyalty_oauth.secret%
            - @jms_serializer
            - @logger
    codewise_loyalty.loyalty_service:
        class: codewise\Bundle\LoyaltyBundle\Service\LoyaltyService
        arguments:
            - @codewise_loyalty.loyalty_api_client
            - @doctrine.orm.entity_manager
            - @jms_serializer
            - @logger
            
#    codewise_message.aws_sqs_client:
#        class: codewise\MessageBundle\Service\AwsSqsClient
#        arguments:
#            - %aws.key%
#            - %aws.secret%
#            - %aws.region%
#            - @validator
#    codewise_loyalty.message_processor:
#        class: codewise\Bundle\LoyaltyBundle\Service\LoyaltyMessageProcessor
#        arguments:
#            - @codewise_message.aws_sqs_client
#            - @validator
#            - @doctrine.orm.entity_manager
#            - @codewise_loyalty.exact_target_soap_client
#            - %codewise_exact_target.API%
#    codewise_loyalty.exact_target_soap_client:
#        class: codewise\MessageBundle\Service\ExactTargetSoapClient
#        arguments:
#            - %exact_target.soap_api.codewise_username%
#            - %exact_target.soap_api.codewise_password%
#            - %exact_target.soap_api.codewise_wsdl%
#    codewise_loyalty.exact_target_message_service:
#        class: codewise\Bundle\LoyaltyBundle\Service\ExactTargetMessageService
#        arguments:
#            - @doctrine.orm.entity_manager
#            - @codewise_loyalty.exact_target_soap_client
